### ISSUE TITLE
The default podcast feed does not validate

### ISSUE THREAD

**Issue by svendahlstrand** [microdotblog/theme-blank#3]
As noticed in [a thread over at the Help Center](https://help.micro.blog/t/podcast-rss-feed-includes-all-posts/2099), the default `/podcast.xml` does not fully validate. This might not be too big of a problem, but some clients, like Inoreader and Reeder, have trouble parsing the file.

Here's a [report of validation errors and warnings](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Flex.micro.blog%2Fpodcast.xml). In addition to what's listed there, some elements are not correctly escaped, which causes trouble in some cases, for example when a podcast's title contains the letter `&`.

A good resource from Apple: [Podcast RSS feed requirements](https://podcasters.apple.com/support/823-podcast-requirements).

This issue is mainly a reminder for myself. I intend to fix it. But, of course, it's free for anyone to try to get rid of the warnings.

**Comment by manton** [comment]
Thanks for flagging this. Here's my podcast feed as an example too, which only complains about `itunes:expicit`:

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ftimetable.manton.org%2Fpodcast.xml

This seems to be a common problem, so I wonder if the iTunes spec changed at some point. Two feeds I just checked have different values than true/false too: atp.fm also uses "no", and www.relay.fm/connected uses "clean".

**Comment by manton** [comment]
I just checked 5 podcasts that I listen to, and _none_ of them validate with the W3C's validator. So before we make any changes, let's confirm that the validator is actually correct. 🙂

**Comment by svendahlstrand** [comment]
Thanks! It looks like the Timetable feed doesn't have any episodes in it; that's probably why we see so few complaints. 😊

And yes, I also remember the use of yes and no, so it's most likely a relatively recent change.

**Comment by svendahlstrand** [comment]
> I just checked 5 podcasts that I listen to, and _none_ of them validate with the W3C's validator. So before we make any changes, let's confirm that the validator is actually correct. 🙂

[It's what Apple states in their documentation](https://help.apple.com/itc/podcasts_connect/#/itcb54353390) if we're talking about the `<itunes:explicit>` element.

**Comment by manton** [comment]
Oops, good catch about my podcast. I'll fix that.

I'm seeing other docs (not Apple's) say to use "yes", "no", or "clean". So my 2 cents would be for us to leave that alone for now, but fix all the other issues, especially the encoding problems. Just don't want things to be _worse_ after fixing it.

**Comment by svendahlstrand** [comment]
Also, a reminder to update https://github.com/microdotblog/plugin-podcast-title with the revised feed layout.

**Comment by svendahlstrand** [comment]
And here's [a pull request](https://github.com/microdotblog/theme-blank/pull/4).

**Comment by svendahlstrand** [comment]
Closing this issue as pull request #4 is merged.
