### ISSUE TITLE
Slow podcast check

### ISSUE THREAD

**Issue by manton** [microdotblog/theme-blank#9]
Hi @svendahlstrand, I've been troubleshooting performance on my blog this week and I think I've tracked it down to this line, figuring out whether to include a podcast feed link:

https://github.com/microdotblog/theme-blank/blob/0b1ddbf60faf0441ffea7fcbfd61fe94c026736d/layouts/partials/microblog_head.html#L10

Haven't thought much about solutions yet, but removing that check seems to make a dramatic improvement. Back down to < 1 minute from 4-5 minutes to build my blog.

**Comment by manton** [comment]
Micro.blog could set a param for whether there are any podcast episodes. My guess is the check isn't _that_ slow, but it's slow enough that if it's run tens of thousands of times, it adds up, because `microblog_head.html` is included everywhere. And it probably can't be cached with `partialCached` because it might vary a little between pages.

**Comment by svendahlstrand** [comment]
Good catch! I'm spoiled with Hugo mostly being smart about caching, so I didn't think about this one. 🤦‍♂️ If Micro.blog could set a parameter, that would definitely be the best solution. If that's hard/too much work, I could look into manually caching the calculation so that it is only done once per site build.

**Comment by manton** [comment]
Not hard at all. I'll add a parameter for it.

**Comment by svendahlstrand** [comment]
Awesome, let me know when it's ready, and I'll make the change, do some local testing and propose a pull request.

Sorry for causing this! 😅 Maybe the test suite should run a benchmark via [`hugo --templateMetrics`](https://gohugo.io/troubleshooting/performance/) to increase the likelihood bottlenecks like this are caught before going to production.

**Comment by manton** [comment]
That's an interesting idea. I did find `--templateMetrics` really useful. Although I think a test would be unlikely to catch serious problems unless the test blog also has a lot of files.

**Comment by manton** [comment]
Okay, I've added a simple boolean for whether there are any audio uploads... Seems to work if I wrap those podcast lines with: `{{ if .Params.has_podcasts }}`

**Comment by svendahlstrand** [comment]
Nice! 🎉 It seems to work for me as well. Here's [the pull request](https://github.com/microdotblog/theme-blank/pull/10).

**Comment by manton** [comment]
Excellent, thanks! Looks good.
